name: app_bundles
description: "A bookmark for your favorite apps"

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  device_apps: ^2.1.1
  flutter:
    sdk: flutter
  flutter_iconpicker: ^3.0.1
  flutter_launch_store: ^1.0.0
  path: ^1.8.0
  receive_sharing_intent: ^1.4.5
  sqflite: ^2.0.0+3
  universal_html: ^2.0.8
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
